title: BSides Aarhus
description: > # this means to ignore newlines until "baseurl:"
  BSides Aarhus is a danish InfoSec event organized and run by the danish non-profit association “BSides Aarhus".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bsidesaar.dk" # the base hostname & protocol for your site

facebook:
  app_id: 

logo: "../css/20120_style/img/icon-large.png"

google_site_verification: googleac29869159bdf7d6.html

include: ['_2020_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BSidesAAR
  - title: linkedin
    url: https://www.linkedin.com/company/bsidesaar/

# Build settings
markdown: kramdown
permalink: pretty
